name: sightseeing_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.1
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  intl: ^0.18.0
  image_picker: ^0.8.6
  path_provider: ^2.0.13
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/compass.jpg
    - assets/compass.jpeg
    - assets/map.jpg
    - assets/nophoto.jpg
    - assets/arrow.png

